language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build ./ -t mrguang123/hello-docker:latest .
  - docker push mrguang123/hello-docker:latest